
baseurl = "https://lbisiunand.netlify.app"
disablePathToLower = false
languageCode = "en-us"
url = '/articles/my-first-article'
title = "Laboratory Of Business Intelligence"
theme = "Hugo-Octopress"

# Disqus shortcode
# Disable comments for any individual post by adding "comments: false" in its frontmatter
# Note it's not under [params] anymore
# disqusShortname = "Your disqus shortname"

# Number of blog posts in each pagination page
paginate = 6

[permalinks]
posts = "/blog/:year-:month-:day-:slug/" # change the post URL to look like the old ones


[markup]
  # Default is startLevel 2 and endLevel 3, we want to render every heading
  [markup.tableOfContents]
    endLevel = 8
    startLevel = 1
  # set the Chroma highlighting options
  # https://gohugo.io/getting-started/configuration-markup/#highlight
  [markup.highlight]
    style = "solarized-dark"
  # if you want to keep using Blackfriday
  # defaultMarkdownHandler = "blackfriday"
  #   [markup.blackFriday]
  #     hrefTargetBlank = true # open links in a new tab

[params]

  # --- Start sidebar options ---
  # Number of last posts that will be displayed in the sidebar - set to 0 or remove to hide this section
  sidebarRecentLimit = 5

  # Sidebar header - passed to markdownify so you can write markdown here
  sidebarHeader = "About Us"

  # Sidebar text also supports markdown
  # New lines can be added with two spaces at the end of line. New paragraphs can be added with two an empty line.
  # when adding two new lines, remember to remove the indentation otherwise the new line will be treated as a codeblock
  sidebarText = """Laboratory of Business Intelligence merupakan salah satu laboratorium riset yang ada di Departemen Sistem Informasi 
  Fakultas Teknologi Informasi Universitas Andalas.
  """
  # Sidebar menu - if true will add a sidebar menu between sidebar text and recent posts
  sidebarMenuEnabled = true
  sidebarMenuHeader = "Sidebar Links"

  # sidebar links
  github = "https://github.com/orgs/Business-Intelligence-Laboratory/dashboard"
  bitbucket = ""
  twitter = ""
  mastodon = ""
  keybase = ""
  stackoverflow = ""
  linkedin = "https://www.linkedin.com/company/laboratory-of-business-intelligence-unand/mycompany/"
  youtube = ""
  facebook = ""
  instagram = "https://www.instagram.com/lbi.si.unand/"

  # --- End sidebar options ---

  # If set to true, navigation menu links will open in a new window with the exception of links to root ("/")
  # If this item does not exist or set to false, then navigation menu links will open in the same window
  navigationNewWindow = false

  # If false, all of blog post will appear on front page (and in pagination)
  truncate = true

  # Author's name (appears in meta tags and under posts)
  author = "Admin"

  # This text appears in the site header under website title
  subtitle = "Departemen Sistem Informasi Universitas Andalas"

  # Search engine URL
  searchEngineURL = "https://www.google.com/search"

  # Text of the "Continue Reading" label. Supports markdown and inline HTML.
  # For example, &rarr; == right arrow.
  continueReadingText = "Baca selengkapnya..."

  # Optional piwik tracking
  # [params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"

  # Switch to true to enable RSS icon link
  rss = true

  # Set to true to use a text label for RSS instead of an icon
  # This is overwritten by the "rss" setting
  textrss = false

  # Website's default description
  description = ""

  # Populate this with your own search keywords - these will appear in the meta tags
  # defaultKeywords = ["keyword1" , "keyword2" , "keyword3" , "keyword4"]

  # CSS override files
  # Paths should be relative to the `static` directory
  # customCSS = ["css/custom.css","css/custom2.css"]

  # 404.html header and text - both support markdown
  notFoundHeader = "There's nothing here"

  notFoundText = """Please either go back or use the navigation/sidebar menus.
  """

  # Set to true to hide ReadingTime on posts
  disableReadingTime = false

  # Set to true to disable downloading of remote Google fonts
  disableGoogleFonts = false

  # Remove or Set to false to use local fonts
  # remoteFonts = false
  
  # Remove or set to false to use FontAwesome CDN, otherwise the theme uses ForkAwesome local fonts.
  # fontAwesome = false

  # Generate taxonomy pages
  generateTaxonomyList = true

  # Sort the taxonomy alphabetically.
  # sortTaxonomyAlphabetical = true

  # Twitter card config
  # Enable with this.
  # twitterCardEnabled = true
  # Don't include the @.
  # twitterCardSite = 
  # twitterCardDomain = "parsiya.net"
  # Don't include the @.
  # twitterCardAuthor = "CryptoGangsta"

  # Set to true to enable compact index. Set to false or remove to go back to classic view.
  # compactIndex = true

  # Set mainSections.
  # mainSections = ["post", "blog"]

  # Site's custom favicon, this is a relative path to the `/static` directory
  # favicon = "newfav.png"

# Google analytics code - remove if you do not have/want Google
# Analytics - needs JavaScript.
# googleAnalytics = "G-MEASUREMENT_ID"


# Menu
# If navigationNewWindow (under [params]) is set to true then all links except root ("/") will open in a new window
# If it does not exist or is set to false then links will open in the same window

[[menu.main]]
  Name = "Home"
  URL = "/"
  weight = -5

[[menu.main]]
  Name = "SOP"
  URL = "/blog/2023-12-03-sop-lab/"
  weight = -5

[[menu.main]]
  Name = "Struktur Organisasi"
  URL = "/blog/2023-12-03-struktur-organisasi/"
  weight = -5

[[menu.main]]
  Name = "Praktikum"
  URL = "blog/2023-12-04-praktikum/"


# Sidebar menus
# Enable with "sidebarMenuEnabled = true" under [params]
# Header text is "sidebarMenuHeader" under [params]

[[menu.sidebar]]
  Name = "About us"
  URL = "/about"
  weight = 2


[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
